apiVersion: v1
kind: ReplicationController

metadata:
  namespace: default
  labels:
    name: npmjs
  name: npmjs

spec:

  replicas: 1
  selector:
    name: npmjs

  template:
    metadata:
      name: npmjs
      labels:
        name: npmjs
    spec:

      containers:
        - name: npmjs
          image: "registry.default.kube.cluster.local/default/npmjs:latest"

          ports:
            - name: http
              containerPort: 3000
          env:
