apiVersion: v1
kind: ReplicationController

metadata:
  labels:
    name: app
  name: app
  namespace: nox73

spec:
  replicas: 1
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - image: registry.default.kube.cluster.local/nox73/app
        env:
          - name: REDIS_HOST
            value: "db"
          - name: REDIS_PORT
            value: "6379"
        name: app
        ports:
        - containerPort: 4567
          protocol: TCP
