apiVersion: v1
kind: Pod

metadata:
  labels:
    name: ping
  name: ping
  namespace: nox73

spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - ping ya.ru
    image: ubuntu
    name: ping
