apiVersion: v1
kind: Service
metadata:
  labels:
    name: app
  name: app
  namespace: nox73

spec:
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    name: app
