apiVersion: v1
kind: ReplicationController

metadata:
  namespace: default
  labels:
    name: gogs
  name: gogs

spec:

  replicas: 1
  selector:
    name: gogs

  template:
    metadata:
      name: gogs
      labels:
        name: gogs
    spec:

      containers:
        - name: gogs
          image: "gogs/gogs"

          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 3000
          env:

          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: data

          nfs:
            server: localhost
            path: /default/gogs
