nginx:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./certs:/etc/nginx/certs
    - ./conf.d:/etc/nginx/conf.d
    - ./http:/usr/share/nginx/html
    - /home/sevenbits/HappyDev:/happydev
  ports:
    - 80:80
  restart: always
