apiVersion: v1
kind: ReplicationController

metadata:
  labels:
    name: jenkins
  name: jenkins
  namespace: default

spec:

  replicas: 1
  selector:
    name: jenkins

  template:
    metadata:
      labels:
        name: jenkins

    spec:
      containers:
        - name: jenkins
          image: "registry.default.kube.ul.home/default/jenkins:latest"

          ports:
            - containerPort: 8080
            - containerPort: 50000

          volumeMounts:
            - name: dockersocket
              mountPath: /var/run/docker.sock
            - name: data
              mountPath: /var/jenkins_home
            - name: kube
              mountPath: /root/.kube

      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: data
          nfs:
            server: 192.168.30.2
            path: /default/jenkins
        - name: kube
          nfs:
            server: 192.168.30.2
            path: /default/kube
