apiVersion: v1
kind: Service

metadata:
  namespace: default
  name: registry
  labels:
    name: registry

spec:

  ports:
  - port: 80
    name: http
    targetPort: 5000
  - port: 443
    name: https
    targetPort: 443

  selector:
    name: registry
