apiVersion: v1
kind: ReplicationController

metadata:
  namespace: default
  labels:
    name: registry
  name: registry

spec:

  replicas: 1
  selector:
    name: registry

  template:
    metadata:
      name: registry
      labels:
        name: registry
    spec:

      containers:
        - name: registry
          image: "registry:0.9.1"

          ports:
            - containerPort: 5000

          env:

            - name: STORAGE_PATH
              value: /var/lib/registry

            - name: REGISTRY_PORT
              value: '5000'

          volumeMounts:
            - name: data
              mountPath: /var/lib/registry

      volumes:
        - name: data

          nfs:
            server: localhost
            path: /default/registry
